name: photoscape
title: Photoscape
version: "3.7"
summary: PhotoScape is a fun and easy photo editing software to fix and enhance photos.
description: |
  PhotoScape is a fun and easy photo editing software that enables you to fix and enhance photos.

  Key Features:

    - Viewer: View photos in your folder, create a slideshow
    - Editor: resizing, brightness and color adjustment, white balance, backlight correction, frames, balloons, mosaic mode, adding text, drawing pictures, cropping, filters, red eye removal, blooming, paint brush, clone stamp, effect brush
    - Batch editor: Batch edit multiple photos
    - Page: Merge multiple photos on the page frame to create one final photo
    - Combine: Attach multiple photos vertically or horizontally to create one final photo
    - Animated GIF: Use multiple photos to create a final animated photo
    - Print: Print portrait shots, carte de visites(CDV), passport photos
    - Splitter: Slice a photo into several pieces
    - Screen Capture: Capture your screenshot and save it
    - Color Picker: Zoom in on images, search and pick a color
    - Rename: Change photo file names in batch mode
    - Raw Converter: Convert RAW to JPG
    - Paper Print: Print lined, graph, music and calendar paper
    - Face Search: Find similar faces on the Internet
grade: stable

base: core18
confinement: strict

architectures:
  - build-on: amd64

environment:
  INSTALL_EXE: "$SNAP/PhotoScapeSetup_V3.7.exe"
  INSTALL_FLAGS: "/S"
  DLLOVERRIDES: "mscoree,mshtml="         # Prevent pop-ups about Wine Mono and Wine Gecko
  # FORCE_WIN32: "true"
  SNAP_TITLE: "$SNAPCRAFT_PROJECT_SUMMARY"
  SNAP_ICON: "$SNAP/meta/gui/icon.png"
  SNAP_SUPPORT_URL: "https://github.com/snapcrafters/photoscape/issues"
  STRICT_SOMMELIER: "1"  # Make Sommelier exit when unset variable is used. (useful to find bugs)

apps:
  photoscape:
    extensions: [ gnome-3-28 ]
    command: bin/sommelier run-exe
    environment:
      RUN_EXE: "/Program Files (x86)/PhotoScape/PhotoScape.exe"
    plugs:
      - home
      - network
      - network-bind
  wineboot:
    extensions: [ gnome-3-28 ]
    command: bin/sommelier wineboot
  winecfg:
    extensions: [ gnome-3-28 ]
    command: bin/sommelier winecfg
    plugs:
      - home
  winetricks:
    extensions: [ gnome-3-28 ]
    command: bin/sommelier winetricks
    plugs:
      - network

parts:
  installer:
    plugin: dump
    source: installer

  sommelier:
    plugin: dump
    source: scripts
    organize:
      'snap-*': bin/
      'sommelier': bin/

  wine-platform:
    plugin: nil
    override-build: |
      snapcraftctl build
      mkdir $SNAPCRAFT_PART_INSTALL/wine-runtime
      mkdir $SNAPCRAFT_PART_INSTALL/wine-platform
  # This part removes all the files in this snap which already exist in
  # connected content and base snaps. Since these files will be available
  # at runtime from the content and base snaps, they do not need to be
  # included in this snap itself.
  #
  # More info: https://snapcraft-utils-library.readthedocs.io/en/latest/lib/cleanup.html 
  #
  cleanup:
    after:  # Make this part run last; list all your other parts here
      - installer
      - sommelier
      - wine-platform
    plugin: nil
    build-snaps:  # List all content-snaps and base snaps you're using here
      - core18
      - gnome-3-28-1804
    override-prime: |
      set -eux
      for snap in "core18" "gnome-3-28-1804"; do  # List all content-snaps and base snaps you're using here
        cd "/snap/$snap/current" && find . -type f,l -exec rm -f "$SNAPCRAFT_PRIME/{}" \;
      done

plugs:
  wine-runtime:
    interface: content
    target: $SNAP/wine-runtime
    default-provider: wine-platform-runtime
  wine-5-stable:
    interface: content
    target: $SNAP/wine-platform
    default-provider: wine-platform-5-stable
