name: photoscape
title: Photoscape
version: "3.7"
summary: PhotoScape is a fun and easy photo editing software to fix and enhance photos.
description: |
  PhotoScape is a fun and easy photo editing software that enables you to fix and enhance photos.

  Key Features:

    - Viewer: View photos in your folder, create a slideshow
    - Editor: resizing, brightness and color adjustment, white balance, backlight correction, frames, balloons, mosaic mode, adding text, drawing pictures, cropping, filters, red eye removal, blooming, paint brush, clone stamp, effect brush
    - Batch editor: Batch edit multiple photos
    - Page: Merge multiple photos on the page frame to create one final photo
    - Combine: Attach multiple photos vertically or horizontally to create one final photo
    - Animated GIF: Use multiple photos to create a final animated photo
    - Print: Print portrait shots, carte de visites(CDV), passport photos
    - Splitter: Slice a photo into several pieces
    - Screen Capture: Capture your screenshot and save it
    - Color Picker: Zoom in on images, search and pick a color
    - Rename: Change photo file names in batch mode
    - Raw Converter: Convert RAW to JPG
    - Paper Print: Print lined, graph, music and calendar paper
    - Face Search: Find similar faces on the Internet
grade: stable

base: core18
confinement: strict

architectures:
  - build-on: amd64

environment:
  INSTALL_EXE: "$SNAP/PhotoScapeSetup_V3.7.exe"
  INSTALL_FLAGS: "/S"
  # TRICKS: "corefonts fontsmooth=rgb gdiplus vcrun2008"
  TRICKS: "gdiplus_winxp"
  WINEPREFIX: "$SNAP_USER_COMMON/.wine"
  DLLOVERRIDES: "mscoree,mshtml=" # Prevent pop-ups about Wine Mono and Wine Gecko
  LC_ALL: "C.UTF-8"
  SNAP_TITLE: "$SNAPCRAFT_PROJECT_SUMMARY"
  SNAP_ICON: "$SNAP/meta/gui/icon.png"
  SNAP_SUPPORT_URL: "https://github.com/snapcrafters/photoscape/issues"

apps:
  photoscape:
    extensions: [ gnome-3-28 ]
    command: bin/start-photoscape
    plugs:
      - hardware-observe
      - home
      - network
      - network-bind
      - process-control
  wineboot:
    command: bin/sommelier $SNAP/bin/wineboot
    plugs:
      - desktop
      - desktop-legacy
      - wayland
      - x11
  winecfg:
    command: bin/sommelier $SNAP/bin/winecfg
    plugs:
      - desktop
      - desktop-legacy
      - wayland
      - x11
  winetricks:
    command: bin/sommelier $SNAP/bin/winetricks prefix="$WINEPREFIX"
    plugs:
      - desktop
      - desktop-legacy
      - network
      - audio-playback
      - wayland
      - x11

parts:
  installer:
    plugin: dump
    source: installer
  add-repos:
    plugin: nil
    override-build: |
      if [ "$SNAPCRAFT_ARCH_TRIPLET" = "x86_64-linux-gnu" ]; then
        dpkg --add-architecture i386
        apt update
      fi
      wget -nc https://dl.winehq.org/wine-builds/winehq.key
      wget -nc https://download.opensuse.org/repositories/Emulators:/Wine:/Debian/xUbuntu_18.04/Release.key
      apt-key add winehq.key
      apt-key add Release.key
      rm -f winehq.key Release.key
      add-apt-repository 'deb https://dl.winehq.org/wine-builds/ubuntu/ bionic main'
      add-apt-repository 'deb https://download.opensuse.org/repositories/Emulators:/Wine:/Debian/xUbuntu_18.04/ ./'
    build-packages:
      - software-properties-common
      - wget

  wine-runtime:
    plugin: nil
    stage-packages:
      # - samba-libs
      # - winbind
      ## wine
      - wine-stable:i386
      ## Required for authentication - Observed in Steam and Track Mania
      - samba-libs:i386
      - winbind:i386
    stage:
      - -etc/init
      - -etc/init.d
      - -etc/logrotate.d
      - -usr/share/apps
      - -usr/share/applications
      - -usr/share/bug
      - -usr/share/doc
      - -usr/share/doc-base
      - -usr/share/debhelper
      - -usr/share/lintian
      - -usr/share/man
      - -usr/share/pixmaps
      - -usr/share/pkgconfig
    after:
      - add-repos

  sommelier:
    plugin: dump
    source: scripts
    organize:
      'snap-*': bin/
      'sommelier': bin/
      'winetricks': bin/
      'zenity': bin/
      'start-photoscape': bin/
    build-packages:
      - curl
    stage-packages:
      - cabextract         # winetricks
      - libnotify4         # yad
      - libnotify-bin      # sommelier
      - perl-base          # winetricks
      - rsync
      - shared-mime-info
      - unzip              # winetricks
      - wget               # winetricks
      - yad                # winetricks
      - x11-xserver-utils  # for xrandr to set virtual desktop
    override-pull: |
      snapcraftctl pull

      curl --silent --show-error --location "https://raw.githubusercontent.com/Winetricks/winetricks/master/src/winetricks" -o winetricks
      chmod +x winetricks
    stage:
      - -etc/init
      - -etc/init.d
      - -etc/logrotate.d
      - -usr/bin/fc-*
      - -usr/bin/gtk-*
      - -usr/lib/dconf/dconf-service
      - -usr/lib/glib-networking/glib-pacrunner
      - -usr/share/GConf
      - -usr/share/aclocal
      - -usr/share/apport
      - -usr/share/apps
      - -usr/share/bash-completion
      - -usr/share/bug
      - -usr/share/debhelper
      - -usr/share/doc
      - -usr/share/doc-base
      - -usr/share/icons/Adwaita
      - -usr/share/icons/Humanity*
      - -usr/share/icons/LoginIcons
      - -usr/share/icons/ubuntu-mono*
      - -usr/share/info
      - -usr/share/kde4
      - -usr/share/lintian
      - -usr/share/menu
      - -usr/share/man
      - -usr/share/perl5
      - -usr/share/pixmaps
      - -usr/share/pkgconfig
    after:
      - add-repos

  # This part removes all the files in this snap which already exist in
  # connected content and base snaps. Since these files will be available
  # at runtime from the content and base snaps, they do not need to be
  # included in this snap itself.
  #
  # More info: https://snapcraft-utils-library.readthedocs.io/en/latest/lib/cleanup.html 
  #
  cleanup:
    after:  # Make this part run last; list all your other parts here
      - installer
      - add-repos
      - wine-runtime
      - sommelier
    plugin: nil
    build-snaps:  # List all content-snaps and base snaps you're using here
      - core18
      - gnome-3-28-1804
    override-prime: |
      set -eux
      for snap in "core18" "gnome-3-28-1804"; do  # List all content-snaps and base snaps you're using here
        cd "/snap/$snap/current" && find . -type f,l -exec rm -f "$SNAPCRAFT_PRIME/{}" \;
      done
